component_depth: 1
languages:
- name: typescript
  production:
    exclude:
      - /templates/*
      - /test/.*
      - /test-helpers/.*
  test:
    include:
      - /test/.*
      - /test-helpers/.*
